In [2]:
import numpy as np
import os
import sys
import matplotlib.pyplot as plt 
#import matplotlib.patches as patches
#os.chdir('/home/alex/Downloads/')
#os.chdir('/home/alex/Downloads/')

===Numpy===
Numerical Python is an open source python library that's used in almost every fied Science and engineering
It's the universal standard for working with numerical data in Python and it's at the core of the scientific Python and PyData ecosystems
The num py API is extensively used in pandas,scipy,matplotlib,scikitlearn,sciki-image,and most other data science and scientific python packages.
The numpy libraray contains multidimesional array and matrix data structures methods to efficiently operate on it
Numpy can be used to perform a wide variety of mathematical operations on arrays.


In [4]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

Python list and Nummpy array
1. Numpy gives us an enoromous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.
2.While Python lists can contains different data types within a single list all of the elements in a Numpy array should be homogenous
3.Numpy arrays are faster and more compact than Python lists.
4.An array consumes less memory and is convieneient to use .
5.Numpy arrays are slower than lists when you append elements to the end


What is an array
An array is a central data structure of the Numpy library.An array is a grid of values.An array can be indexed by a tuple of integers , by booleans, by another array or by integers .The rank of the array is the number of dimensions.The shape of the array is a tuple of integers giving the size of array along each dimension

Vectors , the 1D ArraysVector intilalization
One way to create a Numpy array is to convert a Python list.The type will be auto deducted from the list element types


In [ ]:
a =np.array([1.,2.,3.,4.,5.,6.])
a


array([1., 2., 3., 4., 5., 6.])

In [6]:
#Numpy arrays cannot grow the way list does.No space is reserved  at the end of the array to facilitate quick appennds.So it is a common practice to create a new array and copy the contents of the old array to the new array.either grow a Python list and convert it in a Numpy array when it is ready or to preallocate the necessary spcace with np.zero or np.empty and fill it up with the data. 
b= np.zeros(3,int)
b=np.zeros_like(['a.','b.','c.'])
b.dtype

dtype('<U2')

In [21]:
s=np.arange(1,10,1)
print(s)
s=np.linspace(1,10,2)
print(s)

[1 2 3 4 5 6 7 8 9]
[ 1. 10.]


Generating Random numbers

In [ ]:

print(np.random.randint(1,10,10))# random numbers in integers
np.random.seed(0)
print(np.random.rand(3)) # Generates random numbers from a uniform distribution between 0 and 1.
print(np.random.normal(5,2,3)) # mean=5 and variabliti =2 normal distribution and 3 numbers
print(np.random.uniform(1,10,3)) # random numbers between 1 and 10
print(np.random.randn(3)) # random numbers from normal distribution

[7 9 9 2 7 8 8 9 2 6]
[0.5488135  0.71518937 0.60276338]
[0.4633436  7.66709076 3.31455189]
[9.02595701 9.67296484 4.45097367]
[1.96992445 0.14404357 1.45427351]


In [45]:
np.random.seed(0)
rng=np.random.default_rng()
np.random.seed(0)
print(rng.integers(1,10,10,endpoint=True))
print(rng.random(3))
print(rng.random())
print(rng.standard_normal(3))

[ 5  9  6  9 10  1  5  7  9  4]
[0.78585853 0.04977463 0.61770685]
0.4094555912734609
[-0.20611085  0.11194822  0.11463851]


In [ ]:
a=np.arange(5)
print(a)
print(a[1])
print(a[-2])
print(a[:])
print(a[::-1])
print(a[-2:])
print(np.any(a>3))# any element greater than 3
print(np.all(a>3))# all elements greater than 3
print(a[a>3])
a[a>3]=4
print(a)
np.where(a>3,4,a)
a
a=np.array([1,2,3,4,5])
print("last")
print(a+1)
print(a)
print(a-1)
print(a*2)
print(a/2)
print(a//2)
print(a**2)
print(a%2)
print(1/a)
print(a**a)


[0 1 2 3 4]
1
3
[0 1 2 3 4]
[4 3 2 1 0]
[3 4]
True
False
[4]
[0 1 2 3 4]
last
[2 3 4 5 6]
[1 2 3 4 5]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[ 1  4  9 16 25]
[1 0 1 0 1]
[1.         0.5        0.33333333 0.25       0.2       ]
[   1    4   27  256 3125]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
[1.57079633        nan        nan        nan        nan]
[ 0. nan nan nan nan]
[0.78539816 1.10714872 1.24904577 1.32581766 1.37340077]
[ 1.17520119  3.62686041 10.01787493 27.2899172  74.20321058]
[ 1.54308063  3.76219569 10.067662   27.308

C:\Users\badri\AppData\Local\Temp\ipykernel_11536\1841258234.py:35: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(a))
C:\Users\badri\AppData\Local\Temp\ipykernel_11536\1841258234.py:36: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(a))


In [78]:
a=np.array([1,2,3,4,5])
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.log2(a))
print(np.log10(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
# print(np.arcsin(a))
# print(np.arccos(a))
# print(np.arctan(a))
# print(np.sinh(a))
# print(np.cosh(a))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [33]:
import time
import numpy as np

# Measure time to create and access a NumPy array
start = time.time()
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
end = time.time()
print(f"Time taken to create NumPy array: {end - start} seconds")

start = time.time()
element = a[0, 1]
end = time.time()
print(f"Time taken to access element in NumPy array: {end - start} seconds")
print(f"Accessed element: {element}")

# Measure time to create and access a Python list
start = time.time()
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
end = time.time()
print(f"Time taken to create Python list: {end - start} seconds")

start = time.time()
element = b[0][1]
end = time.time()
print(f"Time taken to access element in Python list: {end - start} seconds")
print(f"Accessed element: {element}")

Time taken to create NumPy array: 0.0010318756103515625 seconds
Time taken to access element in NumPy array: 0.0 seconds
Accessed element: 2
Time taken to create Python list: 0.0 seconds
Time taken to access element in Python list: 0.0 seconds
Accessed element: 2


In [87]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.dot(a,b))
print(np.inner(a,b))
print(np.outer(a,b))
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.reshape(3,2,1))

130
130
[[ 6  7  8  9 10]
 [12 14 16 18 20]
 [18 21 24 27 30]
 [24 28 32 36 40]
 [30 35 40 45 50]]
[[1 2 3]
 [4 5 6]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [90]:
np.zeros((2,3))
np.ones((2,3))
np.full((2,3),5)
np.eye(3)
np.diag([1,2,3,4])


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.sum(a,axis=0)#0 column wise
np.sum(a,axis=1)#1 row wise
np.sum(a)

array([3, 7])